# Generated by Django 3.1.1 on 2020-10-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CargoEmpleado',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='EstadoDepartamento',
        ),
        migrations.DeleteModel(
            name='EstadoInmueble',
        ),
        migrations.DeleteModel(
            name='EstadoReserva',
        ),
        migrations.DeleteModel(
            name='FacturaBoleta',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='MantencionDepartamento',
        ),
        migrations.DeleteModel(
            name='Nacion',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='ReservaDepartamento',
        ),
        migrations.DeleteModel(
            name='ServiciosBasicos',
        ),
        migrations.DeleteModel(
            name='ServiciosExtra',
        ),
        migrations.DeleteModel(
            name='ZonaMueble',
        ),
    ]
