# Generated by Django 3.1.1 on 2020-11-19 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_cargoe'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMueble',
            fields=[
                ('id_estmueble', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_estado', models.CharField(max_length=20)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'estado_mueble',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id_nacionalidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_nacion', models.CharField(max_length=30)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'nacionalidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('fe_pago', models.DateField()),
                ('detalle', models.CharField(max_length=30)),
                ('total_pago', models.IntegerField()),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioDepartamento',
            fields=[
                ('departamento_id_depa', models.OneToOneField(db_column='departamento_id_depa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.departamento')),
            ],
            options={
                'db_table': 'servicio_departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioExtra',
            fields=[
                ('id_servextra', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_serv', models.CharField(max_length=80)),
                ('activo', models.BooleanField()),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'servicio_extra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id_gasto', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_gasto', models.CharField(max_length=40)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'tipo_gasto',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='EstadoInmueble',
        ),
        migrations.DeleteModel(
            name='Nacion',
        ),
        migrations.DeleteModel(
            name='ServiciosBasicos',
        ),
        migrations.DeleteModel(
            name='ServiciosExtra',
        ),
    ]
